import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import Loading from "./loading";
import AuthContext from "./context/AuthContext";
import getCurrentUser from "./actions/getCurrentUser";
import Navigation from "./components/navigation/Navigation";
import SignupModal from "./components/modals/SignupModal";
import LoginModal from "./components/modals/LoginModal";
import ToasterContext from "@/app/context/ToasterContext";


const notSansJP = Noto_Sans_JP({ subsets: ["latin"], weight: "400" });
import { Red_Hat_Display } from 'next/font/google';

const redHat = Red_Hat_Display({
  subsets: ['latin'],
  weight: ['800'],
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Book commerce",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();


  return (
    <html lang="ja">
      <body
        className={`${notSansJP.className} ${redHat.className}`}
      >
        <AuthContext>
          <ToasterContext />
          <SignupModal />
          <LoginModal />
          <Navigation currentUser={currentUser} />

          {/* <SessionProvider> */}

          {/* useSession ()を使う為には、useSession() を使うコンポーネントが <SessionProvider> で囲まれていないといけない */}
          {/* {children}は各フォルダ名/page.tsx のpage,tsxが入るので各ページでuseSession()を使える */}
          {/* SessionProviderはクライアントコンポーネントでしか使えないので、注意が必要 */}
          <Suspense fallback={<Loading />}>{children}</Suspense>
        </AuthContext>
        {/* </SessionProvider> */}

      </body>
    </html>
  );
}
